# Generated by Django 4.2.5 on 2023-10-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_app', '0002_whishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whishlist',
            old_name='cart_item',
            new_name='wishlist_item',
        ),
    ]
