# Generated by Django 4.2.5 on 2023-10-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_app', '0004_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(default='BAD', max_length=10),
            preserve_default=False,
        ),
    ]
