# Generated by Django 4.2.5 on 2023-10-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_app', '0005_coupon_coupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
