# Generated by Django 4.2.5 on 2023-10-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_app', '0007_alter_coupon_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerating',
            name='comment',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
    ]
