# Generated by Django 4.2.5 on 2023-11-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_app', '0008_vehiclerating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerating',
            name='username',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
