# Generated by Django 4.2.5 on 2023-10-05 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.IntegerField()),
                ('payment_status', models.CharField(default='Pending', max_length=250)),
                ('order_date', models.DateTimeField()),
                ('deliver_date', models.DateField()),
                ('return_date', models.DateField()),
                ('order_staus', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('payment_id', models.CharField(blank=True, default=0, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
