# Generated by Django 4.2.5 on 2023-10-05 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_order_staus_order_details_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_cash',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
