# Generated by Django 4.2.5 on 2023-10-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_address_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='listed_vehicles',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
