# Generated by Django 4.2.5 on 2023-10-23 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_listed_vehicles_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='shipping_address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='accounts.address'),
            preserve_default=False,
        ),
    ]
