# Generated by Django 4.2.5 on 2023-11-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_order_details_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='listed_vehicles',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
