# Generated by Django 4.2.5 on 2023-11-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_listed_vehicles_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='listed_vehicles',
            name='owner_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
