# Generated by Django 4.2.5 on 2023-11-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_listed_vehicles_owner_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='listed_vehicles',
            name='rejection_cause',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
