# Generated by Django 4.2.5 on 2023-11-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_address_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='listed_vehicles',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
